# Problem 2
# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#   
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibs <- c(1,2)
while (fibs[length(fibs)-1] + fibs[length(fibs)] <= 4000000) {   # as long as the next number in the sequence is <= 4 million add it to the vector
  fibs <- append(fibs, fibs[length(fibs)-1] + fibs[length(fibs)])
}
print(sum(fibs[fibs%%2 == 0]))  # print the sum of the even number only


